version: '3.8'

services:
  online-db:
    build: .
    container_name: online-db
    restart: unless-stopped
    ports:
      - "3013:3000"
    volumes:
      - .:/app
    networks:
      - webproxy

networks:
  webproxy:
    external: true